Replace var to let in intents.swift for SWIFT 6
Swift 6 strictly checks concurrency when static var for
properties in an App Intent is used.

This resolves the error below,

intents.swift:26:14: error: static property 'searchScopes' is
not concurrency-safe because it is nonisolated global shared
mutable state [#MutableGlobalVariable]