Cherry pick PR #11139: Add build config of devel for tvOS nightly
Refer to original PR: #11139

The devel config will build test artifacts to run on MH's devices.

Fix the error in the tvOS nightly build:

```
com.google.devtools.kokoro.controller.UserException: An error happened while reading and parsing the build config
...
```

Bug: 519668013

(cherry picked from commit b2412eb79e18c21441a5f3a5df346e74addb20d6)