aosp: suppress implicit fallthrough and return-type warnings
Fixes build errors when warnings are set to be considered errors and
switch statements aren't tagging intended fallthrough paths with
[[fallthrough]] and return-type (when not all paths are returning a
value in non-void functions) commonly happening in switch statements
with implicit fallthrough, e.g.:

third_party/crashpad/crashpad/snapshot/cpu_context.cc:222:
   error: non-void function does not return a value in all control
          paths [-Werror,-Wreturn-type]

bool CPUContext::HasShadowStack() const {
  switch (architecture) {
    case kCPUArchitectureX86:
    case kCPUArchitectureARM:
    case kCPUArchitectureARM64:
      return false;
    case kCPUArchitectureX86_64:
      return x86_64->xstate.cet_u.cetmsr != 0;
    default:
      NOTREACHED();
  }
}

Bug: 495203133