Cherry pick PR #11723: starboard: Fix build failure for android-arm_debug
Refer to original PR: #11723

Fix below error in android debug build:

```
../../starboard/shared/starboard/player/filter/testing/audio_frame_discarder_test.cc:149:1: error: 'InstantiateTestCase_P_IsDeprecated' is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use INSTANTIATE_TEST_SUITE_P [-Werror,-Wdeprecated-declarations]
  149 | INSTANTIATE_TEST_CASE_P(
      | ^
../../third_party/googletest/src/googletest/include/gtest/gtest-param-test.h:595:38: note: expanded from macro 'INSTANTIATE_TEST_CASE_P'
  595 |   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
      |                                      ^
../../third_party/googletest/src/googletest/include/gtest/internal/gtest-internal.h:1231:3: note: 'InstantiateTestCase_P_IsDeprecated' has been explicitly marked deprecated here
 1231 | [[deprecated(
      |   ^
1 error generated.
```

Also note INSTANTIATE_TEST_CASE_P has deprecated in Chromium.

Bug: 542940859

(cherry picked from commit 39f3cf75bb5bbf641c6367fc244ccb084eff61a8)