aosp: suppress unused-function warnings
Some third party libraries won't compile because of the warning, such
as third_party/zlib/cpu_features.c:
   error: unused function '_cpu_check_features'

Bug: 380339614