[BACKPORT] Post-increment the erase iterator.
This is a backport change because of the compilation error below,

../../v8/src/wasm/interpreter/wasm-interpreter.cc:189:10: error: no viable overloaded '='
  189 |       it = map_.erase(it);

---
Original Message:

Post-increment the erase iterator.

Unlike STL maps, `absl::flat_hash_map` doesn't return an terator on the
`.erase()` operation.

Follow-up to https://crrev.com/c/7408119.

Change-Id: I9782f61b109bd968b43423df72cf27841dbb7c24
Reviewed-on: https://chromium-review.googlesource.com/c/8/v8/+/7429251
Reviewed-by: Leszek Swirski <leszeks@chromium.org>
Auto-Submit: Jeffrey Yu <yuje@chromium.org>
Reviewed-by: Paolo Severini <paolosev@microsoft.com>
Commit-Queue: Paolo Severini <paolosev@microsoft.com>
Cr-Commit-Position: refs/heads/main@{#104628}