aosp: add missing raw_ptr include
Fixes the following build issue:
  starboard/android/shared/application_android.h:
    error: no template named 'raw_ptr'

Bug: 495203133