[BACKPORT] [on_device_model] Fix build with build_with_tflite_lib=false
This is a backport of https://crrev.com/c/7185063 to do buildable
with build_with_tflite_lib=false .

The error message is

../../third_party/tflite_support/src/tensorflow_lite_support/cc/task/core/base_task_api.h:23:10: fatal error: 'tensorflow/lite/c/common.h' file not found
   23 | #include "tensorflow/lite/c/common.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

and it's caused by https://crrev.com/c/6806229

---
Original CL message:

[on_device_model] Fix build with build_with_tflite_lib=false

//services/on_device_model/safety:bert_safety_model depends on tflite,
and so it cannot be depended on if build_with_tflite_lib is false.

Also fixes the following:
ERROR at //components/optimization_guide/core/inference/BUILD.gn:8:1: Assertion failed.
assert(build_with_tflite_lib)
^-----
See //services/on_device_model/safety/BUILD.gn:15:7: which caused the file to be included.
      "//components/optimization_guide/core/inference:op_resolver",
      ^-----------------------------------------------------------

Change-Id: I2f708f7cbeacfc734c5a8f8840cf6136c9506fc1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7185063
Reviewed-by: Mike Wittman <wittman@chromium.org>
Commit-Queue: jj <jj@chromium.org>
Reviewed-by: Robbie McElrath <rmcelrath@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1552457}