media/base/audio_codecs.h:IWYU
<stdint.h> is included as a part of the CL,
https://crrev.com/c/6998833, in upstream.

We need the hearder because of the error below for now.
Rather than brining the whole CL, it applies the header.

../../media/base/audio_codecs.h:79:36: error: missing '#include <bits/stdint-uintn.h>'; 'uint8_t' must be declared before it is used
   79 |                                    uint8_t* primary_profilec,
      |                                    ^
../../build/linux/debian_bullseye_amd64-sysroot/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h:24:19: note: declaration here is not visible
   24 | typedef __uint8_t uint8_t;
      |                   ^
1 error generated.