Revert "Add optional |clip_rect| param to screenshot functions."
This reverts commit 4d5b69a9fb4ce2b52636055c90b62d37042e08b3.

Reason for revert: Breaks layout_tests

../../cobalt/layout_tests/layout_tests.cc:111:54: error: no matching function for call to 'SnapshotURL'

Change-Id: I0057132b4693dbd23fed12d662b724100dbb273c