BACKPORT: Revert "[Viz] Add CanCreateNativePixmap() to SharedImageManager"
This fixes the linux build:

In file included from ../../gpu/command_buffer/service/shared_image/shared_image_backing.cc:19:
In file included from ../../gpu/command_buffer/service/shared_image/shared_image_factory.h:19:
../../gpu/command_buffer/service/shared_image/shared_image_manager.h:174:35: error: no type named 'VulkanDeviceQueue' in namespace 'gpu'
  174 |                              gpu::VulkanDeviceQueue* device_queue);
      |                              ~~~~~^

---

Original commit message:

This reverts commit 923c52d9973e6959806a2e393c2b54c00c1e2d94.

Reason for revert: This CL has GpuServiceImpl call into
shared_image_manager() [1], but at the point where the method is
called, `gpu_channel_manager_` isn't yet created [2]. This leads to
a crash if we actually executed [1].

[1] https://source.chromium.org/chromium/chromium/src/+/main:components/viz/service/gl/gpu_service_impl.h;l=304-306?q=GpuServiceImpl::shared_image_&ss=chromium
[2] https://source.chromium.org/chromium/chromium/src/+/main:components/viz/service/gl/gpu_service_impl.cc;l=505-516;drc=e3ad182cacc3a02eb6a13091a867815fd17a129c

Original change's description:
> [Viz] Add CanCreateNativePixmap() to SharedImageManager
>
> This CL hides the goop that checks for successful creation of a
> NativePixmap with the given format/usage in
> GpuServiceImpl::IsGMBNV12Supported() behind SharedImageManager. It's
> unfortunately not feasible to move the method wholesale due to the
> call to GpuServiceImpl::IsNativeBufferSupported().
>
> Note: `shared_image_manager()` is guaranteed to be non-null as all
> callers of `InitializeWithHostInternal()` create it internally if
> needed before passing it in.
>
> Change-Id: I3715ec08ea218a47480b7468f686381e9ce2bfbc
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6810905
> Cr-Commit-Position: refs/heads/main@{#1509082}

Change-Id: Iee4e70e37c4743a1c15bec7ab325bac1d5758199
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6917616
Cr-Commit-Position: refs/heads/main@{#1512331}