aosp: add missing link.h include
Bionic defines _Unwind_Ptr in this header.

Fixes the build issue:
  error: unknown type name '_Unwind_Ptr'

Bug: 380339614