Cherry pick PR #12170: Revert "Disable E2E tests on all platforms"
Refer to original PR: #12170

Reverts youtube/cobalt#12061:

"Disabling E2E tests on all platforms due to MobileHarness infra error:
NoSuchMethodError in WebReleaseCodeClientPlugin."

Bug: 548690970

(cherry picked from commit 2064c15a428c4292fe797799715ac26de30c6f0e)