Build fix.
This fixes the build resulting from the warning below, and adds a
missing include highlighted by 'git cl lint'.

error: implicit conversion loses integer precision: 'size_t' (aka
'unsigned long') to 'JDIMENSION' (aka 'unsigned int')

That is a result of the kInvalidHeight dimension being assigned to
jpeg_decompress_struct::output_scanline, which is of type JDIMENSION,
which is typedef'd to 'unsigned int', which is not the same size as
'size_t'.

There is no other use for kInvalidHeight, so this simply changes the
type to JDIMENSION.

Change-Id: I6940713493eec2f61a7f05e95c5fb634c2b03ff9