Revert 167808 - Get rid of use of CreateStringValue in chromeos/ directory.
Reverting because the patch makes clang build failing:
> chrome/browser/chromeos/cros/network_library.cc:380:26:error: C++98 requires an
> accessible copy constructor for class 'base::StringValue' when binding a
>  reference to a temporary; was private [-Werror,-Wbind-to-temporary-copy]
>    SetValueProperty(prop, base::StringValue(str));
etc.

BUG=160586


Review URL: https://chromiumcodereview.appspot.com/11363203

TBR=estade@chromium.org
Review URL: https://codereview.chromium.org/11369258

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@167826 0039d316-1c4b-4281-b951-d872f2087c98