copied_base: fix jni_android build
Add the missing roboelectric buildflags header and build dependencies.

Fixes the following build error:
  copied_base/base/android/jni_android.cc
    error: function-like macro 'BUILDFLAG_INTERNAL_IS_ROBOLECTRIC'
           is not defined