Only depend on oom_intervention on Android TV builds (#7042)
This code was added in #6948 and its usage in shared files is restricted
to `BUILDFLAG(IS_ANDROIDTV)` checks, so there is no need to
unconditionally depend on this target -- in fact, doing so breaks the
tvOS build:

```
../../cobalt/android/oom_intervention/oom_intervention_config.cc:34:19: error: no member named 'swap_total' in 'base::SystemMemoryInfoKB'
  if (memory_info.swap_total == 0) {
      ~~~~~~~~~~~ ^
../../cobalt/android/oom_intervention/oom_intervention_config.cc:44:41: error: no member named 'swap_total' in 'base::SystemMemoryInfoKB'
      static_cast<uint64_t>(memory_info.swap_total * swap_memory_ratio);
                            ~~~~~~~~~~~ ^
```

Bug: 440200929

original-hexsha: 5331f2e41a633b023f2569b236149d63b9d273a4