posix: make the readdir_r wrapper use readdir
The readdir_r call is deprecated. This change make its wrapper
call readdir and mimic readdir_r behavior.

Fixes the build issue:
 starboard/shared/modular/starboard_layer_posix_directory_abi_wrappers.cc:
   error: 'readdir_r' is deprecated: readdir_r is deprecated;
     use readdir instead [-Werror,-Wdeprecated-declarations]
       int retval = readdir_r(dirp->dir, &entry, &result);

Bug: 380339614