Cherry pick PR #12061: Disable E2E tests on all platforms
Refer to original PR: #12061

Disabling E2E tests on all platforms due to MobileHarness infra error:
NoSuchMethodError in WebReleaseCodeClientPlugin.

Bug: 548690970

(cherry picked from commit 7600fc6a40019a854efe1802b4adf28316f3e1bf)