[macOS][Backport] Cherrypick upstream removals of CG_AVAILABLE_BUT_DEPRECATED (#7223)
Cobalt chromium_mac-arm64 and chromium m114 checkout currently do not
build due to

`../../third_party/webrtc/modules/desktop_capture/mac/screen_capturer_mac.mm:35:9:
error: expected function body after function declarator
        CG_AVAILABLE_BUT_DEPRECATED(`

This macro no longer works on macOS 15 and was removed in Chromium
upstream (landed in m119). Cherrypick those changes into Cobalt: [commit
1](https://source.chromium.org/chromium/_/webrtc/src/+/46da472f824aaebfb1352483e9e2145d7bc1483d),
[commit
2](https://source.chromium.org/chromium/chromium/src/+/b63463aa7034239144529066d206d34e30cda570).

I attempted to update the webrtc hash to m138
(https://github.com/youtube/cobalt/pull/7172) and m119, but the
cascading dependency build errors didn't make it worth it.

Bug: 446024838

---------

Co-authored-by: Avi Drissman <avi@chromium.org>