posix: suppress deprecated readdir_r deprecation warnings
Fixes build issues due to the following warnings:

starboard/shared/modular/starboard_layer_posix_directory_abi_wrappers.cc:
  error: 'readdir_r' is deprecated:
    use readdir instead [-Werror,-Wdeprecated-declarations]

Bug: 495203133