[tvos] Fix compiler error in oemcrypto_engine_device_properties_uikit.mm (#12059)
wvcdm::FileSystem needs the qualifier or else it leads to undefined
symbol error due to the wvoec_mock namespace. Also needs starboard media
flag to include wvcdm:: Errors below:

```
ld64.lld: error: undefined symbol: wvoec_mock::CryptoEngine::CryptoEngine(wvoec_mock::scoped_ptr<wvoec_mock::FileSystem>)
>>> referenced by third_party/cobalt/app/tvos/cotvos/branch_27_lts/lib/release/arm64/cobalt.a(oemcrypto_engine_device_properties_uikit.o):(symbol wvoec_mock::CryptoEngine::MakeCryptoEngine(wvoec_mock::scoped_ptr<wvoec_mock::FileSystem>)+0x30)
```
```
../../starboard/tvos/shared/media/oemcrypto_engine_device_properties_uikit.mm:91:41: error: use of undeclared identifier 'wvcdm'
   91 |   explicit CryptoEngineUikit(scoped_ptr<wvcdm::FileSystem> file_system)
```

Bug: 546727215