Cherry pick PR #11822: remove setup cloud sdk (#11865)
Refer to original PR: #11822

Fix the below network error:

```
Error: google-github-actions/setup-gcloud failed with: failed to retrieve versions from https://raw.githubusercontent.com/google-github-actions/setup-cloud-sdk/main/data/versions.json: request timeout: /google-github-actions/setup-cloud-sdk/main/data/versions.json
```

Also replace gsutil with gcloud storage, recommended by GCP.

Bug: 543494079
(cherry picked from commit b969b8befb2adc9c8d35e0a38b9836caab13fa22)

Co-authored-by: Xinan Lin <65635777+linxinan-yt@users.noreply.github.com>