posix: suppress getrandom() unguarded availability warnings
Fixes build errors happening because of unguarded availability warnings.

Fixes:
  starboard/shared/modular/starboard_layer_posix_getrandom_abi_wrappers.cc
    error: 'getrandom' is only available on Android 28 or
           newer [-Werror,-Wunguarded-availability]

Bug: 495203133