Fix errors in xvfb.py and run_test_from_archive.py
run_test_from_archive_smoke_test.py didn't test directory creation so this was
broken. I tested it manually and weeded out the current bug.

For the modification in test_env.py, this is concerning. Without this
modification, I was getting:
Traceback (most recent call last):
  File "../testing/xvfb.py", line 133, in <module>
    sys.exit(main())
  File "../testing/xvfb.py", line 129, in main
    return run_executable(sys.argv[2:], sys.argv[1], os.environ.copy())
  File "../testing/xvfb.py", line 118, in run_executable
    return test_env.run_executable(cmd, env)
AttributeError: 'module' object has no attribute 'run_executable'

Adding a print() or anything else fixed the problem. I'm not sure what's
corrupted on my system.

TBR=cmp@chromium.org,csharp@chromium.org
NOTRY=true
BUG=


Review URL: https://chromiumcodereview.appspot.com/10890027

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@153847 0039d316-1c4b-4281-b951-d872f2087c98