player_worker: Stop constructing |thread_| with an integer (#7043)
Follow-up to #6952, which did the same to some other files but missed
this occurrence.

One of the ideas behind using `std::optional` was to stop using 0 as a
sentinel value; in fact, doing so here breaks the tvOS build:

```
../../starboard/shared/starboard/player/player_worker.cc:113:7: error: no matching constructor for initialization of 'std::optional<pthread_t>' (aka 'optional<_opaque_pthread_t *>')
```

Bug: 438955200

original-hexsha: 7a78f4f2a4f0873560e92505959f3aec8b7143ba