Beginnings of moving more stuff from build_sdk.py to GYP.
Adds a new target to all.gyp: chromium_builder_nacl_sdk
Adds a native_client_sdk gyp file: it depends on nacl_core_sdk from the
native_client repo, but also builds and copies ppapi libraries to the toolchain
directories.

Retry of http://codereview.chromium.org/11363045/
This originally failed here: http://build.chromium.org/p/chromium/builders/Linux%20x64/builds/41342
With the following error:

  init.c:(.text+0x3c): undefined reference to `__libc_setup_tls'
  init.c:(.text+0x2e2): undefined reference to `_dl_init_static_tls'
  init.c:(.text+0x2ec): undefined reference to `_dl_wait_lookup_done'

While building simple_glibc_x86_32.nexe.

My change seems to have tickled a bug in nacl_browser_test.gypi which was using
the link flag -lpthread instead of -pthread. Changing this seems to have fixed
the link failure.

BUG=none
TBR=noelallen@chromium.org
TBR=ncbray@chromium.org

Review URL: https://codereview.chromium.org/11280063

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@168603 0039d316-1c4b-4281-b951-d872f2087c98