aosp: suppress missing-braces warnings
Fixes the errors that happen because some code uses C-style zero
initialization when initializing structs with struct foo = {0};

e.g.:
  starboard/shared/modular/starboard_layer_posix_uname_abi_wrappers.cc:
    error: suggest braces around initialization of
           subobject [-Werror,-Wmissing-braces]
    struct utsname uts = {0};

Bug: 495203133