Require bison 3.
- Remove old bison 2 grammar and and preprocessor conditions
- Specifically check via %require that bison is 3.0 or greater.
- Update CHANGELOG and setup-linux.md accordingly.

The compilation error for bison 2 now will be:

>>>
[1/40] RULE css_grammar: bison_470cf067d6408e34bf2ec6845a0188db grammar.y
FAILED: cd ../../cobalt/css_parser; bison -Wall -Werror "--defines=../../out/linux-x64x11_devel/gen/cobalt/css_parser/grammar_generated.h" "--output=../../out/linux-x64x11_devel/gen/cobalt/css_parser/grammar_impl_generated.h" "grammar.y"
grammar.y:17.10-14: error: require bison 3.0, but have 2.7.12-4996
ninja: build stopped: subcommand failed.
<<<

For patching to 19.lts.1+

Change-Id: I32808d0c72342d8d14916f3e3df4316af601e790