Remove the unused function 'DebugConsoleModeIntToString' .
The unused function was causing a build error:
../../cobalt/browser/debug_console.cc:60:13: error: unused function 'DebugConsoleModeIntToString' [-Werror,-Wunused-function]
Fixed it by removing it.

b/139460185

Change-Id: I1a2df4fee037aadc3300aed85c5ff8f070020436