aosp: add missing base/logging include
Fixes build issues in
copied_base/base/android/java_exception_reporter.cc:
  error: use of undeclared identifier 'ERROR'
  error: use of undeclared identifier 'FATAL'

Bug: 495203133