cobalt/android: Diagnostics for startBrowserProcessesAsync crash (#7034)
Seeing a [native primes
crash](https://primes.corp.google.com/products/5063451/metrics/crashes/clusters/1000000001517437853?sortBy=6&sortOrder=2&duration_seconds=2592000&source=8594998787&reportType=JAVA,NATIVE&trendsTab=overview&timeGranularity=daily):
Abort message:
[15783:15783:0813/<PHONE_NUMBER>:FATAL:jni_android.cc(364)] JNI
exception: MessageQueue.java:335. I believe it has to do with
startBrowserProcessesAsync() in CobaltActivity.java. While I'm not able
to pinpoint the exact cause, I was able to force and replicate the crash
by throwing exceptions in the onSuccess and onFailure calls in
StartupCallback. Adding more exceptions to try and see what exactly is
causing the crash. Current hypotheses include a failed initialization,
low memory, and pressing the back key right after startup.

Bug: 439066169
(cherry picked from commit 1807e4a4b0b2fd556929dd218eea0099b9260af1)