[Rebase M138] Comment out siso config from gclient DEPS hooks (#7519)
Bug: 418842688


This is needed to prevent gclient sync errors when 'Running Hooks':
Syncing projects: 100% (376/376), done.
Running hooks: 61% (58/95) configure_siso
________ running 'python3 src/build/config/siso/configure_siso.py
--rbe_instance projects/cobalt-actions-prod/instances/default_instance'
in '/usr/local/google/home/sideboard/
Code/cobalt-m138-clean'
Need to provide
/usr/local/google/home/sideboard/Code/cobalt-m138-clean/src/build/config/siso/backend_config/backend.star
for your backend projects/cobalt-actions-prod/instanc
es/default_instance
Error: Command 'python3 src/build/config/siso/configure_siso.py
--rbe_instance projects/cobalt-actions-prod/instances/default_instance'
returned non-zero exit status 1 in /usr
/local/google/home/sideboard/Code/cobalt-m138-clean
Need to provide
/usr/local/google/home/sideboard/Code/cobalt-m138-clean/src/build/config/siso/backend_config/backend.star
for your backend projects/cobalt-actions-prod/instanc
es/default_instance