Cherry pick PR #10795: copied_base: remove shouldAddCobaltPrefix() from jni_android
Refer to original PR: #10795

1ccf88fbc56 removed g_add_cobalt_prefix and g_checked_command_line from
copied_base/base/android/jni_android.cc and moved
shouldAddCobaltPrefix() to jni_zero, but didn't remove the old
shouldAddCobaltPrefix from copied_base.

This change removes it to fix the following build issues:

copied_base/base/android/jni_android.cc:
  error: use of undeclared identifier 'g_checked_command_line'
  error: use of undeclared identifier 'g_add_cobalt_prefix'

copied_base is still not using jni_android in copied_base/base/android,
this will be addressed in b/519665580

Bug: 495203133

(cherry picked from commit 7e0352b620db39902ab670aa551466fa5d8ebd3d)