posix: suppress pthread_getname_np unguarded availability warnings
Fixes build errors happening because of unguarded availability warnings:
  starboard/shared/modular/starboard_layer_posix_pthread_abi_wrappers.cc
    error: 'pthread_getname_np' is only available on Android 26
           or newer [-Werror,-Wunguarded-availability]

Bug: 495203133